[database]
url = "postgres://realworld:realworld@localhost:5432/realworld"

[telemetry]
otlp_endpoint = "http://localhost:5081" # OpenObserve OTLP gRPC endpoint

# OpenObserve OTLP/gRPC metadata
otlp_organization = "default"
otlp_stream_name = "default"
otlp_username = "test@po.com"
otlp_password = "test"